CREATE TABLE gym_centers_tb
(
    gym_center_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    gym_name        VARCHAR(255)                            NOT NULL,
    gym_description VARCHAR(255),
    gym_phone       VARCHAR(255),
    gym_email       VARCHAR(255),
    cnpj            VARCHAR(255)                            NOT NULL,
    gym_website     VARCHAR(255),
    gym_image_url   VARCHAR(255),
    gym_address     VARCHAR(255)                            NOT NULL,
    latitude        DOUBLE PRECISION                        NOT NULL,
    longitude       DOUBLE PRECISION                        NOT NULL,
    gym_open_time   time WITHOUT TIME ZONE                  NOT NULL,
    gym_close_time  time WITHOUT TIME ZONE                  NOT NULL,
    owner_id        BIGINT                                  NOT NULL,
    gym_status      VARCHAR(255),
    CONSTRAINT pk_gym_centers_tb PRIMARY KEY (gym_center_id)
);

ALTER TABLE gym_centers_tb
    ADD CONSTRAINT FK_GYM_CENTERS_TB_ON_OWNER FOREIGN KEY (owner_id) REFERENCES ceo_trainers_tb (ceo_trainer_id);