CREATE TABLE work_plans_tb
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    json_plan     TEXT,
    user_id       UUID,
    gym_center_id BIGINT,
    created_at    BYTEA,
    CONSTRAINT pk_work_plans_tb PRIMARY KEY (id)
);

ALTER TABLE work_plans_tb
    ADD CONSTRAINT FK_WORK_PLANS_TB_ON_GYM_CENTER FOREIGN KEY (gym_center_id) REFERENCES gym_centers_tb (gym_center_id);

ALTER TABLE work_plans_tb
    ADD CONSTRAINT FK_WORK_PLANS_TB_ON_USER FOREIGN KEY (user_id) REFERENCES users_tb (user_id);