CREATE TABLE personals_tb
(
    pesonal_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          UUID                                    NOT NULL,
    cref_number      VARCHAR(255)                            NOT NULL,
    specialization   VARCHAR(255),
    years_experience INTEGER,
    CONSTRAINT pk_personals_tb PRIMARY KEY (pesonal_id)
);

ALTER TABLE personals_tb
    ADD CONSTRAINT uc_personals_tb_user UNIQUE (user_id);

ALTER TABLE personals_tb
    ADD CONSTRAINT FK_PERSONALS_TB_ON_USER FOREIGN KEY (user_id) REFERENCES users_tb (user_id);