CREATE TABLE ceo_trainers_tb
(
    ceo_trainer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          UUID                                    NOT NULL,
    years_experience INTEGER                                 NOT NULL,
    CONSTRAINT pk_ceo_trainers_tb PRIMARY KEY (ceo_trainer_id)
);

ALTER TABLE ceo_trainers_tb
    ADD CONSTRAINT uc_ceo_trainers_tb_user UNIQUE (user_id);

ALTER TABLE ceo_trainers_tb
    ADD CONSTRAINT FK_CEO_TRAINERS_TB_ON_USER FOREIGN KEY (user_id) REFERENCES users_tb (user_id);